apiVersion: v2
appVersion: latest
description: Mikrotik (RouterOS) exporter for Prometheus metics
name: mktxp
version: 1.1.4
kubeVersion: ">=1.16.0-0"
keywords:
- mktxp
- mikrotik
- routeros
- prometheus
- metrics
home: https://github.com/akpw/mktxp
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/mikrotik.png
sources:
- https://github.com/akpw/mktxp
- https://github.com/obeone/charts
maintainers:
- name: obeone
  email: obeone@obeone.org
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
annotations:
  artifacthub.io/signKey: |
    fingerprint: B9FE852F28888D27F8C9A11CD33E04CD22E335CE
    url: https://raw.githubusercontent.com/obeone/charts/main/public_key.gpg
  artifacthub.io/maintainers: |
    - name: obeone
      email: obeone@obeone.org
  artifacthub.io/changes: |
    - kind: changed
      description: Update to latest common chart
