version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Europe/Paris
  open-pull-requests-limit: 5
  labels:
  - dependencies
  commit-message:
    prefix: chore(deps)
  groups:
    actions-minor-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    actions-major:
      applies-to: version-updates
      update-types:
      - major
- package-ecosystem: helm
  directories:
  - /charts/cloakbrowser-mcp
  - /charts/cyberchef
  - /charts/dnscrypt-proxy
  - /charts/draw-things
  - /charts/firecrawl
  - /charts/fooocus
  - /charts/libretranslate
  - /charts/mktxp
  - /charts/nfs-server
  - /charts/ollama
  - /charts/olvid-bot
  - /charts/opengist
  - /charts/technitium-dnsserver
  - /charts/transfer.sh
  - /charts/winbox
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: Europe/Paris
  open-pull-requests-limit: 5
  labels:
  - dependencies
  commit-message:
    prefix: chore(deps)
  groups:
    helm-minor-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    helm-major:
      applies-to: version-updates
      update-types:
      - major
