exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme: jekyll-theme-cayman
title: obeone's charts repository
repository: obeone/charts
