apiVersion: v2
appVersion: new-ui
description: Request, review and discover companion app for plex.
name: petio
version: 1.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - petio
  - plex
home: https://petio.tv/
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/petio.png
sources:
  - https://github.com/petio-team/petio
maintainers:
  - name: obeone
    email: obeone@obeone.org
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: mongodb
    version: 11.1.10
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
