apiVersion: v2
appVersion: new-ui
description: Request, review and discover companion app for plex.
name: petio
version: 1.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - petio
  - plex
home: https://petio.tv/
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/petio.png
sources:
  - https://github.com/petio-team/petio
maintainers:
  - name: obeone
    email: obeone@obeone.org
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: mongodb
    version: 12.1.31
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
annotations: 
  artifacthub.io/changes: |
    - kind: changed
      description: Update common library chart to 4.5.2 and mongodb chart to 12.1.31 (mongodb version 5)
    - kind: added
      description: Initial version
