#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/petio-team/petio
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [petio documentation](https://petio.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

# -- Enable and configure mongodb database subchart under this key.
#    For more options see [mongodb chart
#    documentation](https://github.com/bitnami/charts/tree/master/bitnami/mongodb)
#
# The mongodb address to set in petio config will be displayed in intall notes
# @default -- See values.yaml
mongodb:
  enabled: false
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: false
    # storageClass: ""
    # size: 8Gi 

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 7777

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /app/api/config
