apiVersion: v2
appVersion: v10.19.4
description: GCHQ CyberChef [multi-arch]
name: cyberchef
version: 1.3.4
kubeVersion: ">=1.16.0-0"
keywords:
  - cyberchef
home: https://github.com/gchq/CyberChef
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/cyberchef.svg
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/signKey: |
    fingerprint: B9FE852F28888D27F8C9A11CD33E04CD22E335CE
    url: https://raw.githubusercontent.com/obeone/charts/main/public_key.gpg
  artifacthub.io/maintainers: |
    - name: obeone
      email: obeone@obeone.org
  artifacthub.io/changes: |
    - kind: changed
      description: Image repository
