{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded volumes */}}
{{- define "ferdi.hardcodedValues" -}}
{{- if .Values.postgresql.enabled }}
env:   
    DB_CONNECTION: pg
    DB_USER: {{ .Values.postgresql.auth.username }}
    DB_PASSWORD: {{ .Values.postgresql.auth.password }}
    DB_DATABASE: {{ .Values.postgresql.auth.database }}
    DB_HOST: {{ printf "%v-postgresql" .Release.Name }}
    DB_SSL: "false"
{{- end }}
{{- end }}

{{ $_ := mergeOverwrite .Values (include "ferdi.hardcodedValues" . | fromYaml) -}}
{{ include "common.all" . }}
