apiVersion: v2
appVersion: v1.9.1
description: Opengist is a self-hosted Pastebin powered by Git. All snippets are stored in a Git repository and can be read and/or modified using standard Git commands, or with the web interface. It is similar to GitHub Gist, but open-source and could be self-hosted.
name: opengist
version: 1.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - opengist
  - git
  - pastebin
  - gist
  - self-hosted
  - open-source
home: https://github.com/thomiceli/opengist
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/opengist.svg
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.1
annotations:
  artifacthub.io/signKey: |
    fingerprint: B9FE852F28888D27F8C9A11CD33E04CD22E335CE
    url: https://raw.githubusercontent.com/obeone/charts/main/public_key.gpg
  artifacthub.io/maintainers: |
    - name: obeone
      email: obeone@obeone.org
  artifacthub.io/changes: |
    - kind: changed
      description: Better documentation.
