---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.7.1/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/thomiceli/opengist
          # -- image tag
          # this example is not automatically updated, so be sure to use the latest image
          tag: 1.9.1
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables.
        # See [image docs](https://opengist.io/docs/configuration/configure.html) for more details.
        env:
          OG_SSH_GIT_ENABLED: "true"

        # -- environment variables from secrets. For example, it can contains OG_DB_URI for your database connection string.
        envFrom:
          - secretRef:
              name: opengist-secrets
              optional: true

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 80
        targetPort: 6157
        protocol: TCP
      ssh:
        enabled: true
        port: 22
        targetPort: 2222

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - chart-example.local
        secretName: tls-chart-example-local

# -- Configure persistence settings for the chart under this key.
persistence:
  opengist:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: ""
    existingClaim: ""
    size: 10Gi
    globalMounts:
      - path: /opengist
