---
# yaml-language-server: $schema=./values.schema.json

# -- Global parameters for the chart
# Used to configure GPU support and other global settings
global:
  # -- Enable GPU-specific settings (like CUDA paths and GPU resources)
  gpuEnabled: false

controllers:
  main:
    strategy: Recreate

    containers:
      main:
        image:
          # -- Image repository to pull
          repository: libretranslate/libretranslate
          # -- Image tag to pull (use vX.X.X-cuda for GPU builds)
          tag: v1.6.5
          # -- Image pull policy (Always, IfNotPresent, Never)
          pullPolicy: Always

        env:
          # -- Set to "1" to update language models on startup
          LT_UPDATE_MODELS: "1"
          # -- Set to "1" to enable API key usage for authentication
          LT_API_KEYS: "1"

        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http

        resources:
          # -- Resource requests for the main container
          requests:
            cpu: 100m
            memory: 128Mi
          # -- Resource limits for the main container
          limits:
            cpu: 500m
            memory: 512Mi

# -- Service configuration to expose the application internally in the cluster
service:
  main:
    controller: main
    ports:
      http:
        # -- External service port
        port: 80
        # -- Internal container target port
        targetPort: 5000
        # -- Protocol to use (TCP/UDP)
        protocol: TCP

# -- Ingress configuration for external access to the service
ingress:
  main:
    # -- Enable or disable ingress
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - chart-example.local
        # -- Secret containing TLS certificate for the ingress
        secretName: tls-chart-example-local

# -- Persistence volumes configuration for different data types
# Paths are statically defined here. Template logic must occur in templates.
persistence:
  api-keys:
    # -- Enable persistence for API keys database
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Mi
    annotations: {}
    globalMounts:
      - path: /app/db

  cache:
    # -- Enable temporary cache storage
    enabled: true
    type: emptyDir
    cpuPath: /home/libretranslate/.local/cache
    gpuPath: /root/.cache/libretranslate

  db:
    # -- Enable database storage for application data
    enabled: false
    accessMode: ReadWriteOnce
    size: 1Gi
    annotations: {}
    cpuPath: /home/libretranslate/.local/db
    gpuPath: /root/.local/db

  share:
    # -- Enable persistent shared storage for translation models and shared assets
    enabled: true
    accessMode: ReadWriteOnce
    size: 20Gi
    annotations: {}
    cpuPath: /home/libretranslate/.local/share
    gpuPath: /root/.local/share

  files-translate:
    # -- Temporary storage for uploaded translation files
    enabled: true
    type: emptyDir
    path: /tmp/libretranslate-files-translate

# -- Define additional volumes if needed
additionalVolumes: []

# -- Define additional volumeMounts if needed
additionalVolumeMounts: []

# -- Node selector for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment to specific nodes
tolerations: []

# -- Affinity rules to control pod assignment based on node labels
affinity: {}
