apiVersion: v2
appVersion: 2.1.12
description: A flexible DNS proxy, with support for encrypted DNS protocols.
name: dnscrypt-proxy
version: 1.3.1
kubeVersion: ">=1.16.0-0"
keywords:
  - dnscrypt-proxy
home: https://github.com/DNSCrypt/dnscrypt-proxy
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/dnscrypt.png
sources:
  - https://github.com/klutchell/dnscrypt-proxy-docker
  - https://github.com/obeone/charts/
maintainers:
  - name: obeone
    email: obeone@obeone.org
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/signKey: |
    fingerprint: B9FE852F28888D27F8C9A11CD33E04CD22E335CE
    url: https://raw.githubusercontent.com/obeone/charts/main/public_key.gpg
  artifacthub.io/maintainers: |
    - name: obeone
      email: obeone@obeone.org
  artifacthub.io/changes: |
    - kind: changed
      description: Update appVersion
    - kind: changed
      description: Improved README.md
