name: Release Charts

env:
  URL: https://charts.obeone.cloud
  NAME: obeone

on:
  push:
    branches:
      - main

jobs:
  charts:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --dearmor --output keyring.gpg

      - name: Merge main -> gh-pages
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ github.token }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.8.1

      - name: Helm Deps
        run: |
          helm repo add k8s-at-home https://library-charts.k8s-at-home.com
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts
          charts_repo_url: ${{  env.URL }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SIGN: true
          CR_KEY: helm@obeone.org
          CR_KEYRING: keyring.gpg

      - name: Cleanup GPG key
        run: rm keyring.gpg
