apiVersion: v2
appVersion: 1.3.2
description: Ferdi helps you organize how you use your favourite apps by combining them into one application
name: ferdi-server
version: 1.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - ferdi-server
  - ferdi
  - getferdi
home: https://getferdi.com/
icon: https://raw.githubusercontent.com/obeone/charts/main/logo/ferdi.svg
sources:
  - https://github.com/getferdi/server
maintainers:
  - name: obeone
    email: obeone@obeone.org
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
