#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: getferdi/ferdi-server
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [ferdi-server documentation](https://ferdi-server.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  NODE_ENV: development
  APP_URL: https://ferdi.example.com
  # -- pg/mysql/sqlite
  # If you enable embedded postgresql, you can skip these settings.
  DB_CONNECTION: sqlite
  #DB_HOST:
  #DB_PORT: 
  #DB_USER: 
  #DB_PASSWORD: 
  #DB_DATABASE: 
  #DB_SSL: "false"
  MAIL_CONNECTION: smtp
  SMTP_HOST:
  SMTP_PORT: 
  MAIL_SSL: "false"
  MAIL_USERNAME: 
  MAIL_PASSWORD: 
  MAIL_SENDER: ferdi@example.com
  IS_CREATION_ENABLED: "true"
  IS_DASHBOARD_ENABLED: "true"
  IS_REGISTRATION_ENABLED: "true"
  CONNECT_WITH_FRANZ: "false"
  DATA_DIR: /data

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: true
  auth:
    username: ferdi
    password: ferdi
    database: ferdi
  persistence:
    enabled: false
    # storageClass: ""

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3333

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
